### ISSUE TITLE
Option for self-hosted fathom

### ISSUE THREAD

**Issue by BenRoe** [brandonpittman/gridsome-plugin-fathom#1]
Hello,
i use Fathom self-hosted. Would be great, if you add an option to edit the tracker link.

**Comment by brandonpittman** [comment]
Never thought about that. I’ll look into what’s different in the setups.

**Comment by BenRoe** [comment]
`//cdn.usefathom.com/tracker.js` is `//MYDOMAIN.COM/tracker.js`

https://github.com/brandonpittman/gridsome-plugin-fathom/blob/1b3c67810980e642a460f8be29db2978166dce8d/gridsome.client.js#L47

Full tracking code:
```
<!-- Fathom - simple website analytics - https://github.com/usefathom/fathom -->
<script>
(function(f, a, t, h, o, m){
	a[h]=a[h]||function(){
		(a[h].q=a[h].q||[]).push(arguments)
	};
	o=f.createElement('script'),
	m=f.getElementsByTagName('script')[0];
	o.async=1; o.src=t; o.id='fathom-script';
	m.parentNode.insertBefore(o,m)
})(document, window, '//MYDOMAIN.com/tracker.js', 'fathom');
fathom('set', 'siteId', 'XXXXX');
fathom('trackPageview');
</script>
<!-- / Fathom -->
```

**Comment by brandonpittman** [comment]
https://github.com/brandonpittman/gridsome-plugin-fathom/commit/b51ac4be5ec4d5539821a46b5a80ccc09dce8c9b
